# Generated by Django 4.0.4 on 2022-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='model')),
                ('field', models.CharField(max_length=255, verbose_name='field')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'List Display',
                'verbose_name_plural': 'List Display',
                'ordering': ['model', 'order', 'field'],
                'unique_together': {('model', 'order'), ('model', 'field')},
            },
        ),
    ]
