# Generated by Django 4.0.4 on 2022-05-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0003_list_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdisplay',
            name='enabled',
        ),
        migrations.AddField(
            model_name='listdisplay',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='listdisplay',
            name='model',
            field=models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ListDisplayLinkAdmin', 'ListDisplayLinkAdmin'), ('ListFilterAdmin', 'ListFilterAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='listdisplaylink',
            name='model',
            field=models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ListDisplayLinkAdmin', 'ListDisplayLinkAdmin'), ('ListFilterAdmin', 'ListFilterAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='listfilter',
            name='model',
            field=models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ListDisplayLinkAdmin', 'ListDisplayLinkAdmin'), ('ListFilterAdmin', 'ListFilterAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='model'),
        ),
    ]
