# Generated by Django 4.0.4 on 2022-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0004_list_display_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdisplaylink',
            name='enabled',
        ),
        migrations.AddField(
            model_name='listdisplaylink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
