# Generated by Django 4.0.4 on 2022-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0005_list_display_link_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listfilter',
            name='enabled',
        ),
        migrations.AddField(
            model_name='listfilter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
