# Generated by Django 4.0.2 on 2022-02-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_configuration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuration',
            table=None,
        ),
    ]
