# Generated by Django 4.0.2 on 2022-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_configuration_hide_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='group',
            field=models.CharField(default='', max_length=255, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True, verbose_name='value'),
        ),
    ]
