# Generated by Django 4.0.2 on 2022-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_user_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='group',
            field=models.CharField(default='', max_length=255, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True, verbose_name='Value'),
        ),
    ]
