# Generated by Django 4.0.2 on 2022-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_configuration_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_redirect_page',
            field=models.CharField(blank=True, max_length=255, verbose_name='Redirect page after login'),
        ),
    ]
