# Generated by Django 4.0.2 on 2022-02-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.team')),
            ],
            options={
                'verbose_name': 'Week',
                'verbose_name_plural': 'Weeks',
                'ordering': ['-starting_date', '-ending_date', 'team'],
            },
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('team', 'starting_date'), name='week_unique_team_starting_date'),
        ),
    ]
