# Generated by Django 4.0.2 on 2022-02-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0003_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('is_holyday', models.BooleanField(default=False)),
                ('permit_hours', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.employee')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.week')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-week', '-date', 'employee'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('week', 'employee', 'date'), name='shift_unique_date_employee_date'),
        ),
    ]
