# Generated by Django 4.0.2 on 2022-02-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0009_configuration_delay_after_save_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
    ]
