# Generated by Django 4.0.2 on 2022-02-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0014_employee_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_holiday',
            field=models.BooleanField(default=False, verbose_name='Is holiday'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Is present'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='permit_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Permit hours'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.week', verbose_name='Week'),
        ),
    ]
