# Generated by Django 4.0.2 on 2022-02-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0017_week_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-week', '-date', 'employee'], 'permissions': [('can_access_reports', 'Can access reports')], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
    ]
