# Generated by Django 4.0.2 on 2022-02-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0018_shift_permission_can_access_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-starting_date', '-ending_date', 'team'], 'permissions': [('can_reopen_weeks', 'Can reopen weeks')], 'verbose_name': 'Week', 'verbose_name_plural': 'Weeks'},
        ),
    ]
