# Generated by Django 4.0.4 on 2022-06-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0022_team_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Numeric'), (2, 'Checkbox on left'), (3, 'Checkbox on right'), (4, 'Select')], default=True, verbose_name='Type')),
                ('minimum', models.PositiveIntegerField(default=0, verbose_name='Minimum value')),
                ('maximum', models.PositiveIntegerField(default=0, verbose_name='Maximum value')),
                ('values', models.TextField(blank=True, verbose_name='Values')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'ordering': ['order', 'name'],
            },
        ),
    ]
