# Generated by Django 4.0.4 on 2022-06-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0024_team_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.extra', verbose_name='Extra')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workhours.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Shift Extra',
                'verbose_name_plural': 'Shift Extras',
                'ordering': ['-shift', 'extra'],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftextra',
            constraint=models.UniqueConstraint(fields=('shift', 'extra'), name='shiftextra_unique_shift_extra'),
        ),
    ]
