# Generated by Django 4.0.4 on 2022-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0025_shift_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='extras',
            field=models.ManyToManyField(related_name='shift_extras', to='workhours.shiftextra'),
        ),
    ]
