version: '3'

services:
  web:
    container_name: django-work-hours_web
    image: nginx:1.21.3-alpine
    ports:
      - 8000:8000/tcp
    depends_on:
      - backend
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx

  backend:
    container_name: django-work-hours_backend
    image: ilmuflone/django-work-hours:0.2.0
    environment:
      - SERVER_PORT=8080
    expose:
      - 8080
    volumes:
      - ./static:/app/static
      - ./database.sqlite3:/var/lib/django-work-hours.sqlite3
      - ./settings_container.py:/app/project/settings_container.py

